"""empty message

Revision ID: 02edf7cf0631
Revises: d9e73f614bcf
Create Date: 2023-03-30 11:05:17.478060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02edf7cf0631'
down_revision = 'd9e73f614bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('experience_level',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('experience_level',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
